# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ee279200a32528a94afb4bd2cc8772dc8d413ad14b8055eefc6a98430729e3659312005a4d3768e42258c93c4a523b21468dec951a9442447ef3252f94be35c

test:
  secret_key_base: 8506629ec5400f36bf800658287928f25c40534a48d22f5e2d46e51b92a026cf3eadc7e7d57b973e38d66d1dd750d98f6d1ba7ecdc7e937173d57f4be21aa3db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
